/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IBridgeFactoryInterface extends utils.Interface {
  contractName: "IBridgeFactory";
  functions: {
    "allTokens(uint256)": FunctionFragment;
    "allTokensLength()": FunctionFragment;
    "changeMigrator(address)": FunctionFragment;
    "copy(address,uint256,string)": FunctionFragment;
    "deployToken(uint256,string,string,string,uint8)": FunctionFragment;
    "migrate(address)": FunctionFragment;
    "migrator()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allTokensLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeMigrator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "copy",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deployToken",
    values: [BigNumberish, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "migrate", values: [string]): string;
  encodeFunctionData(functionFragment: "migrator", values?: undefined): string;

  decodeFunctionResult(functionFragment: "allTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allTokensLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeMigrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "copy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "migrate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "migrator", data: BytesLike): Result;

  events: {};
}

export interface IBridgeFactory extends BaseContract {
  contractName: "IBridgeFactory";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBridgeFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { token: string }>;

    allTokensLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    changeMigrator(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    copy(
      _addr: string,
      _chainID: BigNumberish,
      _originAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployToken(
      _chainId: BigNumberish,
      _originAddress: string,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    migrate(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    migrator(overrides?: CallOverrides): Promise<[string]>;
  };

  allTokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  allTokensLength(overrides?: CallOverrides): Promise<BigNumber>;

  changeMigrator(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  copy(
    _addr: string,
    _chainID: BigNumberish,
    _originAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployToken(
    _chainId: BigNumberish,
    _originAddress: string,
    _name: string,
    _symbol: string,
    _decimals: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  migrate(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  migrator(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    allTokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    allTokensLength(overrides?: CallOverrides): Promise<BigNumber>;

    changeMigrator(arg0: string, overrides?: CallOverrides): Promise<void>;

    copy(
      _addr: string,
      _chainID: BigNumberish,
      _originAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    deployToken(
      _chainId: BigNumberish,
      _originAddress: string,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    migrate(arg0: string, overrides?: CallOverrides): Promise<void>;

    migrator(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    allTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allTokensLength(overrides?: CallOverrides): Promise<BigNumber>;

    changeMigrator(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    copy(
      _addr: string,
      _chainID: BigNumberish,
      _originAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployToken(
      _chainId: BigNumberish,
      _originAddress: string,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    migrate(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    migrator(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    allTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allTokensLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeMigrator(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    copy(
      _addr: string,
      _chainID: BigNumberish,
      _originAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployToken(
      _chainId: BigNumberish,
      _originAddress: string,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    migrate(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    migrator(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
